### ISSUE TITLE
kacheryhub home page blank

### ISSUE THREAD

**Issue by DradeAW** [kacheryhub/kachery-doc#22]
Hi,

I'm trying to get some of the raw data on spikeforest to test my algorithm against gold-standard spike sorters.

I've been following the installation instruction on this page (using the `conda` method): https://github.com/kacheryhub/kachery-doc/blob/main/doc/hostKacheryNode.md
But when I open https://www.kacheryhub.org/home, it's blank and there is no node showing up and no logging possible.
Here is a screenshot:
![Screenshot from 2021-11-03 16-12-31](https://user-images.githubusercontent.com/3465310/140088512-f7f673b4-ae80-43bb-886c-f43ecd9d8ae9.png)

I ran `kachery-daemon-start --label spikeforest --owner [...]`
And `kachery-daemon-info` correctly outputs a Node ID and says "You have access to this daemon".

Am I doing something wrong?
Thanks,

Drade

**Comment by magland** [comment]
@Dradeliomecus thanks for the report. There was a problem causing the login button to be disabled on kacheryhub. You should now be able to sign in on kacheryhub and configure your node.

**Comment by DradeAW** [comment]
When I click "Sign in", it redirects me to the Google API and tells me:

```
Error 403 : org_internal
This client is restricted to users within its organization

[The following I translated from French, I hope it's accurate]
Request details
This section's content was given by the app developer. Google did not examine or validate it.

If you are the app developer, make sure the details of this request respect the following Google rules:
- openid.realm:
- response_type: permission id_token
- redirect_uri: storagerelay://https/www.kacheryhub.org?id=auth910579
- ss_domain: https://www.kacheryhub.org
- include_granted_scopes: true
- client_id: 985276542804-hf5arsrefnpbf5hqctnvnj30jp9qni0i.apps.googleusercontent.com
- fetch_basic_profile: true
- gsiwebsdk: 2
- access_type: online
- scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid
```

**Comment by magland** [comment]
Sorry about that. Please try again now.

**Comment by DradeAW** [comment]
Thanks, it works!
